### ISSUE TITLE
Support for Lego Train Motor 88011

### ISSUE THREAD

**Issue by Niwa1980** [RaspberryPiFoundation/python-build-hat#104]
Please add support for Lego Train Motor 88011.

https://www.lego.com/en-us/product/train-motor-88011

**Comment by chrisruk** [comment]
This is now present in the 'main' branch of this repo, called 'PassiveMotor'
When there is a new pypi release, it will also be part of that.

**Comment by Niwa1980** [comment]
Thanks for Info. It's working.
