### ISSUE TITLE
Support for LEGO 88005 Powered Up Light

### ISSUE THREAD

**Issue by Niwa1980** [RaspberryPiFoundation/python-build-hat#105]
Please add support for LEGO 88005 Powered Up Light.

https://www.lego.com/en-us/product/light-88005

**Comment by chrisruk** [comment]
Hi, I've just added support for the light, I will get it added to the next pypi release.  You can test it now like so though:

```
pip3 uninstall buildhat
pip3 install git+https://github.com/RaspberryPiFoundation/python-build-hat.git
```

Then in your script:

```
import time
from buildhat import Light
light = Light("D")
light.on()
time.sleep(1)
light.off()
```

**Comment by chrisruk** [comment]
Hi,

Just wondering if you're still having problems with this?

I've just been testing turning on/off the light on a clean boot
and also after unplugging / plugging in the light after.

Thanks

**Comment by Niwa1980** [comment]
Hi,

sorry for the delay. I checked the latest version with no success. This code:

```
from buildhat import Hat
hat = Hat()
devices = hat.get()
print(devices)
```

produces the following output: 

```
{'A': {'typeid': -1, 'connected': False, 'name': 'Disconnected'}, 'B': {'typeid': -1, 'connected': False, 'name': 'Disconnected'}, 'C': {'typeid': -1, 'connected': False, 'name': 'Disconnected'}, 'D': {'typeid': -1, 'connected': False, 'name': 'Disconnected'}}
```

It is irrelevant at which port the leds are connected. There are not recognized.

I will check now if the leds are working properly.

Cheers

**Comment by Niwa1980** [comment]
I ordered a replacement. After delivery I will test again.

**Comment by mutesplash** [comment]
Light support doesn't work.  This seems to be a firmware problem.  I plugged it into the 51515 hub and was able to set the light levels from 0-10, so the light is not broken.

**Comment by mutesplash** [comment]
The **old** Firmware 1630165527 2021-08-28T16:45:27+01:00 will power on the lights, but not list them in the device list.

**Comment by joerk** [comment]
Upgrade to 0.5.7 release but the Light 88005 on port D is not detected. 

`pi@pi4:~/projects/lego_buildhat $ /bin/python /home/pi/projects/lego_buildhat/hat.py
{'A': {'typeid': 75, 'connected': True, 'name': 'Motor'}, 'B': {'typeid': 63, 'connected': True, 'name': 'ForceSensor'}, 'C': {'typeid': 62, 'connected': True, 'name': 'DistanceSensor'}, 'D': {'typeid': -1, 'connected': False, 'name': 'Disconnected'}}`

Any hints?

**Comment by chrisruk** [comment]
Could everyone tell me what PSU you're using please with the buildhat? I had issues with the lights when using USB-C PSU, but with my own barrel jack PSU, they do work for me.

**Comment by Niwa1980** [comment]
I am using the official PSU: https://www.raspberrypi.com/products/build-hat-power-supply/.

**Comment by chrisruk** [comment]
Thanks, do you mind telling me where you bought the light from? (Just wondering if there maybe more than one version)

**Comment by Niwa1980** [comment]
From the official Lego online shop.

**Comment by Niwa1980** [comment]
Lego support tells me, that the product will be available at the end of january. I ordered a replacement in december 2021 for the supposedly defect component.

**Comment by mutesplash** [comment]
Official 8V 6A RPi PSU

**Comment by mutesplash** [comment]
Also bought the light from lego.com

**Comment by chrisruk** [comment]
Thanks all, just ordered some from lego.com to have a look at

**Comment by joerk** [comment]
> Thanks, do you mind telling me where you bought the light from? (Just wondering if there is maybe more than one version) I will see if I could possibly order one from the seller someone here used, to do some more debugging.

From the local lego store - cologne; germany. See attached the bag ... 
![IMG_4616](https://user-images.githubusercontent.com/12663507/149829899-25f21224-ec6d-4441-ab9c-c21e1ff3717f.jpg)
![IMG_4617](https://user-images.githubusercontent.com/12663507/149829909-14e55d07-1836-432b-926c-aacf1c2909d6.jpg)
![IMG_4618](https://user-images.githubusercontent.com/12663507/149829916-bb4ff09b-d61a-40e6-9cda-0b9964ca738b.jpg)

**Comment by joerk** [comment]
> Official 8V 6A RPi PSU



> I am using the official PSU: https://www.raspberrypi.com/products/build-hat-power-supply/.

Same here.

**Comment by Niwa1980** [comment]
Any news on this?

**Comment by mutesplash** [comment]
`P0: connected to passive ID 8`

Shows up and works with the Light class!

Can you set the brightness levels like you can on the Spike hub?

**Comment by chrisruk** [comment]
@mutesplash sure, just added a brightness function:

```
import time
from buildhat import Light

l = Light('A')
bright = 0
step = 1
while True:
    l.brightness(bright)
    bright += step
    if bright == 100 or bright == 0:
        step *= -1
    time.sleep(0.01)
```

It uses 0 - 100 for consistency with the brightness on the distance sensor.

**Comment by Niwa1980** [comment]
I will try to test it tomorrow.

Thanks in advance.

**Comment by Niwa1980** [comment]
It's working. Great work and thanks again. 👍

**Comment by joerk** [comment]
> @Niwa1980 @joerk Does this work for you? Great success over here!

Yes! Take me some time to setup the local build env. Now I'm prepared for deep dive ;-) Regards Joerk
