### ISSUE TITLE
Error message when running serial command

### ISSUE THREAD

**Issue by Narshil94** [RaspberryPiFoundation/python-build-hat#106]
I followed the getting started document and ran the recommended python script. The first time i got a response along the lines of no motor connected on port A. Now it runs the script with no output at all.

I tried connecting to the board directly through serial0.

The list command returns Error.

The version command responds with BuildHAT bootloader version 1631704133 2021-09-15T12:08:53+01:00

Is there somewhere where I can find a more recent bootloader version?

**Comment by chrisruk** [comment]
Can you show me which python script you're running, along with the behaviour you're seeing with the script

Thanks

**Comment by chrisruk** [comment]
Closing for now, please re-open if you're still facing an issue

**Comment by zer044** [comment]
Just in-case its useful to anybody else. The issue was creating the image on a RPI3B+ then running the image on a RPI3 A+. This does not work and for some reason remains broken when you move the sd card back to a RPI3B+. 

Running on a RPI3B+ without moving it to another RPI works fine.
