### ISSUE TITLE
Get voltage info

### ISSUE THREAD

**Issue by iwanimsand** [RaspberryPiFoundation/python-build-hat#107]
The command `vin` exists in the serial protocol [Raspberry Pi Build HAT Serial Protocol](https://datasheets.raspberrypi.com/build-hat/build-hat-serial-protocol.pdf) and prints the voltage present on the input power jack.

When I work with a battery, I want to constantly check the voltage and thus protect against a deep discharge.

I haven't found a method in the official python library to get this information. Would it be possible to implement such a method in the python library?

**Comment by chrisruk** [comment]
Yup, that sounds a good plan, will have a look at your pull request soon, thanks!

**Comment by chrisruk** [comment]
Thanks for your pull request, I've just merged it
