### ISSUE TITLE
Any possibility communicate with spike/RE hub over USB 

### ISSUE THREAD

**Issue by vibin18** [RaspberryPiFoundation/python-build-hat#116]
Please implement a method to communicate with spike/RE Hub over USB/ bluetooth, which allows the access to LED matrix and IMU.

**Comment by mutesplash** [comment]
Since this library is designed to run on the RaspberryPi and access the BuildHAT, you would just include a different library (such as https://github.com/smr99/lego-hub-tk) in your program to access both of them in the same program (yours)

**Comment by vibin18** [comment]
Thank you.
