### ISSUE TITLE
Firmware blob

### ISSUE THREAD

**Issue by jrddunbr** [RaspberryPiFoundation/python-build-hat#132]
Hi,

I noticed in the repository that it comes packaged with a firmware blob, a signature/checksum, and a version, which is loaded into the device on every load of the library.

I was curious if there's another repository with the source code for said blob available, or if it will be available in the future. The main chip on-board the hat is almost surely the RP2040, so I figured that there is probably some nice source code for it that could be useful in other similar projects with the Pico.

Thanks!

**Comment by chrisruk** [comment]
At the moment there are no plans to release the firmware source, but will update if this changes

Thanks

**Comment by mutesplash** [comment]
That's unfortunate.  Is there a specific reason to keep this secret like there is with other Raspberry Pi blobs such as the Broadcom controllers?

**Comment by jrddunbr** [comment]
@mutesplash FWIW, the blob is MIT licensed (the blob doesn't have a different license listed, and the repo is published with a blanket MIT license), so there's nothing saying you can't just decompile it (it's just ARM (v6?), Ghidra could decompile it) and PR/fork the source code that results, or just use the blob in whatever use you want (eg, you can probably deploy it to the Pico and reverse engineer it). (This is not legal advice; attempt at your own risk)

Or, they could take out the middleman and just publish the source to the blob. It makes no sense to keep this blob closed source, unlike with the mentioned Broadcom IP that the foundation doesn't own the rights to.

If I had to guess, there's probably some NDA with Lego that they have to not publish the source for the blob to prevent people from interfacing with Lego, because Lego is pretty tight on the LPF2 connector specification, and has virtually zero SDK/HDK information published for the platform (which is equally frustrating because it's a bunch of basic STM microcontrollers in all the motors/sensors/hubs with also unpublished blobs). But the RPi Foundation probably can't confirm or deny that they are under NDA so they just give us the above message (read: never).

I'll probably just desolder the LPF2 connectors from this and make an Arduino breakout/shield instead, and open source the source code to that.

**Comment by chrisruk** [comment]
Closing for now, will alter the readme if things change
