### ISSUE TITLE
How can I use 2 Build hat boards on one GPIO?

### ISSUE THREAD

**Issue by Qulaiemiu** [RaspberryPiFoundation/python-build-hat#158]
1. How to connect 2 Build Hat boards?
2. How work woth python libs and ports?
3. How connect another boards and devices to 40-pin GPIO?
4. It is possible to use one power for 2 Build Hat boards?

**Comment by mutesplash** [comment]
1. You can not
2. How to use Python is outside the scope of this project
3. I couldn't find much with a quick search, leading me to believe that just connecting them over Ethernet would be faster
4. No

**Comment by Qulaiemiu** [comment]
It is possible to connect 5 devices through Raspberry?
