### ISSUE TITLE
PiJuice compatibility

### ISSUE THREAD

**Issue by lrauldan** [RaspberryPiFoundation/python-build-hat#183]
I've got both PiJuice and BuildHat and I was wondering if I can power my Pi with PiJuice and BuildHat with a separate 7.5v battery pack. My electrical engineering knowledge is limited and I couldn't figure out if I risk burning all 3 boards if I do that or not.

**Comment by chrisruk** [comment]
I'm not really familiar with the PiJuice, it looks like it is designed to supply 5V to the pi itself though.

I've powered an older revision of the build HAT with a battery pack like - https://www.batteryspace.com/Battery-holder-Li-Ion-18650-Battery-Holder-2S1P-With-2.6-long-20AWG.aspx with 2x 18650 batteries and attached the wires to a screw terminal with a 'cctv' style plug, to plug directly into the build hat.

Hope that helps
