### ISSUE TITLE
Is it possible to control a lego power function motor with the build hat?

### ISSUE THREAD

**Issue by HannahFehringer** [RaspberryPiFoundation/python-build-hat#185]
Hello,

basically my issue title already sums up my question: Is it possible to control a lego power function motor with the build hat?

There do exist some cable which allow a connection between powered up and power function devices. However, if I connect my lego pf motor with the raspberry pi build hat, I get the following error message: 
`buildhat.exc.DeviceError: There is not a Motor connected to port A (Found PassiveMotor)`

This tells me that it found a motor, but not the expected one. Does anybody have experience with this issue?

**Comment by mutesplash** [comment]
You need to use the PassiveMotor class and not the Motor class.

**Comment by chrisruk** [comment]
Yes, that's correct, there's an example at the bottom of https://buildhat.readthedocs.io/en/latest/buildhat/passivemotor.html

**Comment by chrisruk** [comment]
Will close this now, feel free to open another issue if there's anything else
