### ISSUE TITLE
running motor simultaneously

### ISSUE THREAD

**Issue by schultz77** [RaspberryPiFoundation/python-build-hat#200]
Hi there,

I'am trying to run four lego motors with raspberry pi 4 and build-hat simultaneously.
Using MotorPair it worked well for 2 motors. Is there any possibility to run 2 motor pairs simultaneously?

This is probably not a bug but a feature.
Thx in advance!

**Comment by mutesplash** [comment]
Have you tried it?

**Comment by schultz77** [comment]
Hi mutesplash,

When I  execute run_to_position for one motor pair (A, B) and then for the other one (C, D)  they run after each other. First A. B then C, D.
I would like to have a motor quadruple A, B, C, D.

Is it somehow possible and I misunderstood the documentation? 

Thank you!

**Comment by mutesplash** [comment]
Have you specified to run them nonblocking?

**Comment by schultz77** [comment]
Thank you for your quick reply!
I'll try it and give you feedback at the latest tomorrow!

**Comment by schultz77** [comment]
Hey mutesplash,

thank You very much. It works!

**Comment by schultz77** [comment]
see comments above

**Comment by schultz77** [comment]
Hey mutesplash,

thank You very much. It works!
