### ISSUE TITLE
How is the firmware written?

### ISSUE THREAD

**Issue by Eisverygoodletter** [RaspberryPiFoundation/python-build-hat#207]
How is the file
https://github.com/RaspberryPiFoundation/python-build-hat/blob/main/buildhat/data/firmware.bin
created and how would I go about writing my own firmware? 
I understand that this file is loaded into the build hat by `serinterface.py` every time the build hat is loaded, but I don't know how this firmware file could be created. 
I'm experimenting with using a non-official sensor that doesn't have an ID code specified by the firmware documentation at https://datasheets.raspberrypi.com/build-hat/build-hat-serial-protocol.pdf

**Comment by mutesplash** [comment]
That would be real nice but as far as I can tell the firmware is signed by developers at the Raspberry Pi company and _presumably_ the RP2040 is set to not load any third party firmware.  It would be a huge upgrade to get the firmware on github, even if we couldn't do anything with it, for debugging and reasonable feature requests.

**Comment by grega** [comment]
We are aware of these issues, but not currently able to make any promises or commitments. Will update if that changes.

**Comment by mutesplash** [comment]
But is Raspberry Pi... _interested_ in resolving the issue?

**Comment by grega** [comment]
Yes, but it is potentially complex. Am hoping to be able to explore the matter more over the next couple of months.

**Comment by Eisverygoodletter** [comment]
Thanks for the response! I might settle on just using the official sensors for now.

**Comment by mutesplash** [comment]
@grega Any new information on this front?

**Comment by grega** [comment]
We're expecting to have some news on this front around mid-January. Apologies for the delays!

**Comment by mutesplash** [comment]
News!  Thank you!

**Comment by laurensvalk** [comment]
> Yes, but it is potentially complex. Am hoping to be able to explore the matter more over the next couple of months.
> 
> We're expecting to have some news on this front around mid-January. Apologies for the delays!

Over at Pybricks we'd still be happy to make a community-based open source firmware replacement using the Pybricks device drivers, which covers all known LEGO motors and sensors.

We _shouldn't need any of the original proprietary source code_ for the hat -- just a way to sign binaries for compatibility with the hat's bootloader. If the Raspberry Pi Foundation team wants to get in touch, please feel free to reach out at team@pybricks.com.

**Comment by grega** [comment]
@laurensvalk yep was planning on getting in touch about this soon 👍 am almost certain we'll be able to do something here in the not-too-distant future...

**Comment by grega** [comment]
Imminent. Waiting on a couple of factors not in my direct control but hoping it won't be more than a couple of weeks...

**Comment by vodorok** [comment]
Hi @grega, do you have any updates?

**Comment by tlaguz** [comment]
Hello @grega, are there any updates?

**Comment by AndyA** [comment]
Hi @grega - any update on this? Thanks.

**Comment by grega** [comment]
@mutesplash glad to hear! Really pleased to have been able to make this happen finally, and I hope that it will open up many more opportunities for everyone...

**Comment by AndyA** [comment]
Fantastic news. Thank you @grega

**Comment by vodorok** [comment]
Hi @grega, kudos to you for not forgetting the conversation in this obscure issue. These are great news!
