### ISSUE TITLE
Build HAT Python Library PDF 'color and distance sensor' product number

### ISSUE THREAD

**Issue by SimUKdev** [RaspberryPiFoundation/python-build-hat#91]
_Reposting of issue from https://github.com/raspberrypi/documentation/issues/2232 to this correct project repo as requested by @aallan_

In the PDF file "Build HAT Python Library" at https://datasheets.raspberrypi.com/build-hat/build-hat-python-library.pdf on PDF page 8/14 (numbered page 7) there is a section titled "ColorDistanceSensor", and the first paragraph of that section has a link to a Lego website page for "LEGO® Color and Distance Sensor".

The link text currently says "LEGO® Color and Distance Sensor 45605", but "45605" is the product number for the item listed immediately before this one in the PDF. The link correctly goes to the product page, which confirms that "LEGO® Color and Distance Sensor" has product code "88007".

Corrected link text would be "LEGO® Color and Distance Sensor 88007"

Image of issue
![138444119-8c03bb26-8241-45d7-9efd-12ba4bb6d2f0](https://user-images.githubusercontent.com/52102399/138445886-1798e852-62f4-495d-b4f6-bc3e7a224cd1.png)

**Comment by chrisruk** [comment]
Thanks for your comment @SimUKdev it looks like the documentation has been fixed now.
