### ISSUE TITLE
intermittent error when first creating a Motor object

### ISSUE THREAD

**Issue by topshed** [RaspberryPiFoundation/python-build-hat#93]
I've now seen this a few times on different Raspberry Pis using the Build HAT.

`m = Motor('C')`
> Exception in thread Thread-128:
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/pi/.local/lib/python3.7/site-packages/buildhat/serinterface.py", line 205, in loop
>     line = self.ser.readline().decode('utf-8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 18: invalid continuation byte

Running the program again (or trying the same line again if using the REPL) then works without error.

**Comment by chrisruk** [comment]
I just got an error when instantiating a motor too, where it would hang.

I just looked at the serial dump:

```
Timed out waiting for data
Error
BHBL>
````

Will try and do some more digging into this.

**Comment by chrisruk** [comment]
Closing for now, as the unicode issue should hopefully be fixed now
